services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - kolos
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/kolos

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=kolos
      - MYSQL_ROOT_PASSWORD=Oxymore
    ports:
      - 3306:3306
    networks:
      - kolos
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -pOxymore"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
          - ./:/docker-entrypoint-initdb.d
          - db:/var/lib/mysql
          
volumes:
    db:
      driver: local
        

networks:
  kolos:
    driver: bridge

