services:
  kolos:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=kolos
      - MYSQL_ROOT_PASSWORD=Oxymore
    ports:
      - 3306:3306
    # volumes:
    #       - ./:/docker-entrypoint-initdb.d
    #       - kolos:/var/lib/mysql
          
volumes:
    kolos:
      driver: local
        
    
