name: build and push the api image to docker hub
on:
    push:
        branches:
            - dev

jobs:
    Build-Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PWD }}

            - name: Build
              run: docker build -t kolos .

            - name: Tag
              run: docker tag kolos:latest nicolasdrp/kolos:latest

            - name: Push
              run: docker push nicolasdrp/kolos:latest
